### ISSUE TITLE
Displaying parameter values

### ISSUE THREAD

**Issue by farvardin** [jpcima/ADLplug#45] opened 2018-12-28 22:59 UTC
I could be pleasant to have in the UI the current value of the parameter we are editing:

- either from a pop-up which display the value
- or from a single window in the UI (updated with the name of the parameter and the current value), like Dexed does in the bottom left corner for instance, or like Helm does in the top left corner.

It's especially useful for comparing the precise values from an other piece of software (for example adlib tracker II), or for better understanding of the instrument we're editing (like for the frequency multiplication)

**Comment by jpcima** [comment] 2018-12-29 11:33
Added: value display for knob and slider parameters. Before calling this complete, I want to add:
1. have step resolution of all controls <= unity (not the case of level, OPN ADSR)
2. display while a control is hovered, like in Dexed

**Comment by jpcima** [comment] 2018-12-29 12:36
Mouse hovering is done.
For step resolution I'll look a bit later as it has a bit of complication involved.

**Comment by jpcima** [comment] 2018-12-29 12:45
@farvardin PS if you are interested to have an importer of Adlib Tracker instrument or other formats, post a request over at [OPL3BankEditor](https://github.com/Wohlstand/OPL3BankEditor), if it doesn't have that support already.
I'll look into it depending how complicated the task shows to be. Myself I've no experience with operating this tracker software.

**Comment by jpcima** [comment] 2018-12-29 23:36
Not exactly. The problem is that based on mouse wheel events, the control is sometimes going to increase or decrease by more than 1. It's difficult to land on a precise value in this condition; It would like the increment to max at 1.

The problem is in the underlying library, it does not permit to set a fixed increment for the mouse.
Instead it's computed as I formula between the component's screen size and the value the mouse is sending. There doesn't seem to exist another fix than to go modify some code inside juce framework.

**Comment by farvardin** [comment] 2018-12-30 20:48
ok I understand. Anyway now we have more precise informations about the status of the knobs and sliders and it's much better!

I've seen it's possible to import/export instrument with OPL3BankEditor and also with Adlib Tracker, using the common format .sbi (not with 4-op, but 2-op is fine).

**Comment by jpcima** [comment] 2018-12-30 21:02
>I've seen it's possible to import/export instrument with OPL3BankEditor and also with Adlib Tracker,

ADLplug has also had for a moment the ability to load sbi files directly; it was a feature made on a musician's request.

> using the common format .sbi (not with 4-op, but 2-op is fine).

Both OPL3Bankeditor and ADLplug must support 4-op instrument import.
If you can provide a sample which doesn't work as should, please post for analysis.

**Comment by farvardin** [comment] 2018-12-31 17:51
It wasn't clear how I wrote it, but I meant I could export in .sbi with OPL3bankEditor, but it failed for loading those 4-op instruments (made with open3bankeditor) in Adlib Tracker, but I'm not sure Adlib Tracker can support 4-op instruments in sbi format. 

So far it looks like for having 4-op in Adlib Tracker II, you do this by loading 2 different 2-op instruments and connecting them together, so I suppose it's an expected behavior.

**Comment by jpcima** [comment] 2019-01-01 14:53
The sliders and knobs are updated in the latest, now they support unity resolution with the mouse wheel.

**Comment by farvardin** [comment] 2019-01-02 18:08
It's just perfect now, thank you veeeeeeery much!!

**Comment by jpcima** [comment] 2019-01-02 20:07
Great :+1:

**Closed by jpcima** 2019-01-02 20:07 UTC
